### ISSUE TITLE
from negate import Negator gives this error: ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

### ISSUE THREAD

**Issue by sairamsubramaniam** [dmlls/negate#14]
**Describe the bug**
Described in the below sections.

<br>**To Reproduce**
I am using python 3.8.10 . I did a `pip install negate` and then opened a python3.8.10 shell on a linux terminal and ran `from negate import Negator` and got the error pasted in the below section.

<br>**Expected behavior**
immediately after a `pip install negate`, I did a `from negate import Negator` and I got this error below:
```python3
Python 3.8.10 (default, Nov 22 2023, 10:22:35) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from negate import Negator
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/<my_username>/.local/lib/python3.8/site-packages/negate/__init__.py", line 1, in <module>
    from .negate import Negator
  File "/home/<my_username>/.local/lib/python3.8/site-packages/negate/negate.py", line 10, in <module>
    import spacy
  File "/home/<my_username>/.local/lib/python3.8/site-packages/spacy/__init__.py", line 6, in <module>
    from .errors import setup_default_warnings
  File "/home/<my_username>/.local/lib/python3.8/site-packages/spacy/errors.py", line 3, in <module>
    from .compat import Literal
  File "/home/<my_username>/.local/lib/python3.8/site-packages/spacy/compat.py", line 39, in <module>
    from thinc.api import Optimizer  # noqa: F401
  File "/home/<my_username>/.local/lib/python3.8/site-packages/thinc/api.py", line 1, in <module>
    from .backends import (
  File "/home/<my_username>/.local/lib/python3.8/site-packages/thinc/backends/__init__.py", line 17, in <module>
    from .cupy_ops import CupyOps
  File "/home/<my_username>/.local/lib/python3.8/site-packages/thinc/backends/cupy_ops.py", line 16, in <module>
    from .numpy_ops import NumpyOps
  File "thinc/backends/numpy_ops.pyx", line 1, in init thinc.backends.numpy_ops
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

<br>**Additional context**
This is my linux distro version:
> Distributor ID: Neon
> Description:    KDE neon User - 5.24
> Release:        20.04
> Codename:       focal

**Comment by dmlls** [comment]
Hi @sairamsubramaniam, thanks for reporting!

This issue seems to be stemming from `numpy`. It looks like it arises particularly when using Python 3.8. I haven't been able to find a conclusive answer to the problem, but maybe you can try [this proposed solution](https://stackoverflow.com/a/66138833/14683209) to see if that solves it?

**Comment by sairamsubramaniam** [comment]
Yes, your suggestion did resolve it @dmlls ! Thank you so much for looking into it and suggesting the solution.
I ran an upgrade for numpy. Here is the log for reference:
```
user@user:~$  pip install --upgrade numpy
Collecting numpy
  Using cached numpy-1.24.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.21.2
    Uninstalling numpy-1.21.2:
      Successfully uninstalled numpy-1.21.2
Successfully installed numpy-1.24.4
```

**Comment by dmlls** [comment]
@sairamsubramaniam glad it helped!
